chore: change the project structure
microsoftgraph/msgraph-sdk-typescript-core pull request #43
Opened 2024-02-14 13:05 UTC by musale

TODO:
- [ ] fix tests
- [ ] fix build

2024-02-14 13:10 UTC, baywet requested changes
Thanks for starting this.
~~I believe we need to update the package.json for the main/types fields etc...~~
Maybe the npmignore as well
~~And why are we deleting the lock?~~

2024-02-15 08:42 UTC, musale commented
> Thanks for starting this. I believe we need to update the package.json for the main/types fields etc... Maybe the npmignore as well And why are we deleting the lock?

I'll update all those as well. Normally I use `yarn` for local development. I assumed that this project is using `npm` cos of the `package-lock.json`. The deleted lock file is `yarn.lock`. However, I propose using `yarn` because of it's many modern features like zero installs for development.

2024-02-15 13:26 UTC, baywet commented
@musale if we switch to yarn, I'll request that we do so across all repositories (kiota-typescript, this one, the service libs, etc...)
The challenge I previously had was that ONLY kiota-typescript had been setup with yarn and that was inconsistent across repos (and annoying during local dev loops). Let's treat this change separately for now please.
I have stricken my comments about the package fields since it was already done, as well as the one about the lock file, sorry about the confusion.
I think your TODOs and the other comments I've made are still applicable.

2024-02-15 14:08 UTC, baywet commented on .github/workflows/build_test_validate.yml
>          - run: npm run build
shouldn't we have a step to run the update version script (JS) here?

2024-02-15 14:18 UTC, musale commented on package.json
> +    "build": "npm run updateVersion && npm run prettier:check && npm run clean && npm run build:compile",
@baywet the build step runs the script to update the version first before "building" commands.

2024-02-15 14:23 UTC, musale commented
> @musale if we switch to yarn, I'll request that we do so across all repositories (kiota-typescript, this one, the service libs, etc...) The challenge I previously had was that ONLY kiota-typescript had been setup with yarn and that was inconsistent across repos (and annoying during local dev loops). Let's treat this change separately for now please. I have stricken my comments about the package fields since it was already done, as well as the one about the lock file, sorry about the confusion. I think your TODOs and the other comments I've made are still applicable.

In this case, then let's leave it. I did change the test framework from mocha and chai to https://vitest.dev. There weren't any tests but from the other js repo, we would need to test async and some browser code in here, so I picked a framework that supports all of that out of the box with minimal setup for es module project. I also added husky which installs git hooks that locally run prettier and lint commands before you committing.

2024-02-15 15:11 UTC, baywet submitted a review, later dismissed
Thanks for all the great changes here! My TypeScript knowledge is a bit rusty, and that ecosystem keeps changing so fast...

2024-02-28 11:31 UTC, baywet approved these changes

2024-02-28 11:34 UTC, merged